### ISSUE TITLE
Installing cdo on Windows

### ISSUE THREAD

**Issue by dfifield** [IsaakBM/NACECC_workshop_repo#1]
Hi Isaak,

Thanks for all your hard work on this workshop!

I had some issues getting cdo installed under Ubuntu and WSL on Windows 11. 

I found I had to do:
`sudo apt upgrade`

after
`sudo apt update`

When I did that I got this message:

> Failed to take /etc/passwd lock: Invalid argument on upgrade 

I followed the sequence of commands in the first answer to this question to fix the problem:

[https://superuser.com/questions/1803992/getting-this-error-failed-to-take-etc-passwd-lock-invalid-argument](url)

**Comment by IsaakBM** [comment]
That's great, thanks @dfifield 

I’ll add that set of solutions to the eBook now!
