### ISSUE TITLE
Setting DISPLAY variable for VcXsvr under Windows

### ISSUE THREAD

**Issue by dfifield** [IsaakBM/NACECC_workshop_repo#2]
Executing this command did not work for me (Windows 11):

`export DISPLAY=$(grep nameserver /etc/resolv.conf | awk '{print $2}'):0.0`

This resulted in a mangled DISPLAY variable because my /etc/resolv.conf contains more than one nameserver row.

Instead I simply used my machine name:

`export DISPLAY=hostname:0.0`

where _hostname_ is replaced with your computer name. This can be found by right-clicking on the **Start Menu**, choosing **System**, and then the name is listed under **Device name**.

**Comment by IsaakBM** [comment]
That's great, thanks @dfifield!

I’ll add it to the eBook now!
